/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;

// RN 0.77 removed `ViewManagerWithGeneratedInterface`; it was only a marker interface used by
// codegen. We don't need it for compilation or runtime behavior.
public interface RNGestureHandlerRootViewManagerInterface<T extends View> {
  void setUnstable_forceActive(T view, boolean value);
}
